version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running tests...
      - npm run test
      - echo Building the application...
      - npm run build
      - echo Exporting static files...
      - npm run export
  post_build:
    commands:
      - echo Syncing files to S3...
      - aws s3 sync out https://appweb-s.s3.amazonaws.com/ --delete
artifacts:
  files:
    - "**/*"
  base-directory: out
cache:
  paths:
    - "node_modules/**/*"
