version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run test && npm run build
      - sed -i 's|/_next/|./_next/|g' ./out/index.html

  post_build:
    commands:
      - echo Syncing files to S3...
      - aws s3 sync out s3://appweb-s/out --delete
artifacts:
  files:
    - "**/*"
  base-directory: out
cache:
  paths:
    - "node_modules/**/*"
